server:
  port: 17777
  servlet:
    context-path: /api/scaffold
  shutdown: graceful
spring:
  application:
    name: phoenix-scaffold
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.156.24:3306/scaffold?characterEncoding=utf-8
    password: W&l1203@
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: 192.168.156.24
      port: 6379
      password: W&l1203@
springdoc:
  api-docs: # 是否开启接口文档
    enabled: true
    path: /v3/api-docs
  swagger-ui: # 持久化认证数据，如果设置为 true，它会保留授权数据并且不会在浏览器关闭/刷新时丢失
    persistAuthorization: true
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.phoenix.scaffold.controller